name: HardcourseCheckpoints
version: '1.0-SNAPSHOT'
main: com.hardcourse.hardcoursecheckpoints.HardcourseCheckpoints
api-version: '1.20'
commands:
  makecpcommand:
    description: Make a checkpoint
    usage: /makecp
    aliases: [makecp, makecheckpoint]